name: stale

on:
  schedule:
    - cron: "0 5 * * 1"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    name: stale
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale issues
        uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10
        with:
          days-before-issue-stale: 45
          days-before-issue-close: 14
          days-before-pr-stale: -1
          stale-issue-label: stale
          exempt-issue-labels: roadmap,design,security
